# Imagen base
FROM python:3.11-slim

# Crear y definir directorio de trabajo
WORKDIR /app

# Copiar archivos del backend
COPY ./backend /app

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer puerto interno
EXPOSE 2521

# Comando de inicio
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "2521"]

