# Etapa 1: build de React
FROM node:20 AS build

WORKDIR /app
COPY ./frontend /app
RUN npm install && npm run build

# Etapa 2: servir con Nginx
FROM nginx:1.27

# Copiar archivos generados
COPY --from=build /app/dist /usr/share/nginx/html

# Copiar configuración personalizada
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 2521

CMD ["nginx", "-g", "daemon off;"]

